version: '3'

services:
  django:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - react

  react:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
