# Generated by Django 4.1.7 on 2023-10-01 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
                ('categories', models.ManyToManyField(to='panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=-90.0, message='Latitude must be greater than or equal to -90.0'), django.core.validators.MaxValueValidator(limit_value=90.0, message='Latitude must be less than or equal to 90.0')])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=-180.0, message='Longitude must be greater than or equal to -180.0'), django.core.validators.MaxValueValidator(limit_value=180.0, message='Longitude must be less than or equal to 180.0')])),
            ],
        ),
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_from', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('transportation_type', models.CharField(choices=[('BU', 'Bus'), ('TR', 'Train')], default='BU', max_length=2)),
                ('departure_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='panel.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='images',
            field=models.ManyToManyField(to='panel.image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.location'),
        ),
        migrations.AddField(
            model_name='destination',
            name='open_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.opentime'),
        ),
    ]
