# Generated by Django 4.2.4 on 2024-03-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageGallery',
        ),
    ]
