# Generated by Django 4.1.7 on 2023-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='images',
            field=models.ManyToManyField(to='panel.image'),
        ),
    ]
