# Generated by Django 4.2.4 on 2023-08-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_location_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
                ('categories', models.ManyToManyField(to='panel.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.location')),
                ('open_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.opentime')),
                ('public_transport_schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.publictransportline')),
            ],
        ),
    ]
