# Generated by Django 4.2.4 on 2023-08-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_destination_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='public_transport_schedules',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.publictransportline'),
        ),
    ]
