# Generated by Django 4.2.4 on 2023-08-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_destination_public_transport_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.location'),
        ),
    ]
