# Generated by Django 4.2.4 on 2023-08-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0009_remove_destination_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_from', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('transportation_type', models.CharField(choices=[('BU', 'Bus'), ('TR', 'Train')], default='BU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
                ('categories', models.ManyToManyField(to='panel.category')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.location')),
                ('open_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.opentime')),
                ('public_transport_schedules', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.publictransportline')),
            ],
        ),
    ]
