# Generated by Django 4.2.4 on 2023-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_destination_public_transport_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransportline',
            name='departure_for',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
