# Generated by Django 4.2.4 on 2023-09-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_publictransportline_departure_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='public_transport_schedules',
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='departure_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.destination'),
        ),
    ]
