# Generated by Django 4.2.4 on 2023-09-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_remove_destination_public_transport_schedules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictransportline',
            name='departure_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='panel.destination'),
        ),
    ]
